#!/bin/sh
 #PBS -N helloworld
 #PBS -l nodes=2:ppn=2,walltime=00:10:00
 #PBS -q dev
 #PBS -j oe
 #PBS -o $PBS_JOBNAME-$PBS_JOBID.log
cat $PBS_NODEFILE 
cd $PBS_O_WORKDIR
module purge mpich2/intel/1.4.1
 module load openmpi/gcc/1.4.2
 mpiexec -np 4 ./hello
